# Generated by Django 3.1.5 on 2021-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('father_name', models.CharField(max_length=150, verbose_name='Ata adi')),
                ('phone_number', models.CharField(max_length=150, verbose_name='telefon nomresi')),
                ('age', models.CharField(max_length=150, verbose_name='yasiniz')),
                ('education', models.CharField(max_length=150, verbose_name='tehsiliniz')),
                ('city', models.CharField(max_length=150, verbose_name='sheher')),
                ('job_practice', models.CharField(max_length=150, verbose_name='Ish Tecrubeniz')),
                ('vacation_name', models.CharField(max_length=150, verbose_name='Muraciet etdiyiniz vakansiya')),
                ('ability', models.CharField(max_length=150, verbose_name='bacariqlariniz')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV-lər',
            },
        ),
    ]
