# Generated by Django 3.1.5 on 2021-03-05 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ad')),
                ('logo', models.ImageField(upload_to='uploads/partners/', verbose_name='Logo')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name='Mətn')),
            ],
            options={
                'verbose_name': 'Partnyor',
                'verbose_name_plural': 'Partnyorlar',
            },
        ),
    ]
