# Generated by Django 3.1.5 on 2021-03-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='link',
        ),
    ]
