# Generated by Django 3.1.5 on 2021-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='uploads/banners/', verbose_name='reklam baneri')),
            ],
        ),
    ]
