# Generated by Django 3.1.5 on 2021-04-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='cover',
            new_name='left_cover',
        ),
        migrations.AddField(
            model_name='banner',
            name='right_cover',
            field=models.ImageField(default=True, upload_to='uploads/banners/', verbose_name='reklam baneri'),
            preserve_default=False,
        ),
    ]
