# Generated by Django 3.1.5 on 2021-03-05 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Haqqimizda', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Haqqimizda Melumat')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kredit şərtləri', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Zemanet haqqinda Melumat')),
            ],
        ),
        migrations.CreateModel(
            name='EhomeAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=300, verbose_name='Filialin adi')),
                ('address', models.CharField(max_length=300, verbose_name='unvan')),
                ('email', models.EmailField(max_length=254, verbose_name='Ehome mail unvani')),
                ('phone_number', models.CharField(max_length=50, verbose_name='telefon nomresi')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ehome zəmanəti', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Zemanet haqqinda Melumat')),
            ],
        ),
        migrations.CreateModel(
            name='Logistication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Çatdırılma və quraşdırılma', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Çatdırılma haqqinda Melumat')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ödəmə şərtləri', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Ödəmə şərtləri haqqinda Melumat')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='abonentin email unvani')),
            ],
            options={
                'verbose_name_plural': 'Abune olunmus istifadeciler',
            },
        ),
    ]
