# Generated by Django 3.1.5 on 2021-03-15 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Layihe şərtləri', max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Layiheler haqqinda Melumat')),
                ('main_image', models.ImageField(upload_to='uploads/projects')),
                ('image', models.ManyToManyField(to='about.ProjectImages')),
            ],
        ),
    ]
