# Generated by Django 3.1.5 on 2021-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide/uploads/', verbose_name='Şəkil')),
                ('link', models.URLField(max_length=500, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
            },
        ),
    ]
