# Generated by Django 3.1.5 on 2021-03-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyad')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon nömrəsi')),
                ('taksit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taksit')),
                ('shipping_address', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Çatdırılacaq ünvan')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction id')),
                ('taksit_transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Taksit Transaction id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='products.Product')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='Ad')),
                ('lastname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=30, verbose_name='Əlaqə nömrəsi')),
                ('taksit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Taksit')),
                ('ordered_date', models.DateTimeField(verbose_name='Sifarişin edilmə tarixi')),
                ('shipping_address', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Çatdırılacaq ünvan')),
                ('amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Məbləğ')),
                ('status', models.CharField(blank=True, choices=[('approved', 'Qəbul edilib'), ('being_delivered', 'Çatdırılır'), ('recieved', 'Təhvil verilib')], default='approved', max_length=40)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('taksit_transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Taksit Transaction id')),
                ('items', models.ManyToManyField(blank=True, to='orders.OrderItem', verbose_name='Məhsullar')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Təsdiqlənmiş Sifariş',
                'verbose_name_plural': 'Təsdiqlənmiş Sifarişlər',
            },
        ),
    ]
