# Generated by Django 3.1.5 on 2021-03-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210307_2148'),
        ('orders', '0002_auto_20210314_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
