# Generated by Django 3.1.5 on 2021-03-05 12:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kateqoriya adı AZ')),
                ('image', models.ImageField(blank=True, upload_to='uploads/category/', verbose_name='Şəkil')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childeren', to='products.category', verbose_name='Üst Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Məhsulun adı AZ')),
                ('artikul', models.CharField(max_length=250, verbose_name='Məhsulun artikulu')),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/', verbose_name='Məhsulun əsas şəkli')),
                ('features', ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name='Məhsulun xüsusiyyətləri')),
                ('delivery', ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name='Çatdırılma və quraşdırılma')),
                ('payment', ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name='Ödəniş')),
                ('loan_terms', ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name='Kredit şərtləri')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Məhsulun qiyməti')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='Əlavə edilmə tarixi')),
                ('in_stock', models.BooleanField(default=False, verbose_name='Anbarda?')),
                ('is_new', models.BooleanField(default=False, verbose_name='yenidir?')),
                ('like_votes', models.IntegerField(default=0)),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Məhsulun kateqoriyası')),
                ('colors', models.ManyToManyField(to='products.Color', verbose_name='mehsulun sekilleri')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.country')),
                ('images', models.ManyToManyField(blank=True, to='products.PostImage', verbose_name='Məhsulun şəkilləri')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Endirimdə olan məhsul',
                'verbose_name_plural': 'Endirimdə olan məhsullar',
            },
        ),
        migrations.CreateModel(
            name='PopularCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Populyar kateqoriya',
                'verbose_name_plural': 'Populyar kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Musterinin adı')),
                ('email', models.EmailField(max_length=254)),
                ('commentary', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='BestSellerProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Çox satılan',
                'verbose_name_plural': 'Çox satılanlar',
            },
        ),
    ]
