# Generated by Django 3.1.5 on 2021-03-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='products.Color', verbose_name='mehsulun rengleri'),
        ),
    ]
