# Generated by Django 3.1.5 on 2021-03-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210307_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rest_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Mehsulun endirimli qiymeti'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='endirim faizi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Yenidir?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Məhsulun oz qiyməti'),
        ),
    ]
