# Generated by Django 3.1.5 on 2021-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210314_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artikul',
            field=models.CharField(blank=True, max_length=250, verbose_name='Məhsulun artikulu'),
        ),
    ]
