# Generated by Django 3.1.5 on 2021-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210314_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='brend_name',
            field=models.CharField(max_length=100, verbose_name='marka adi'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=100, verbose_name='reng'),
        ),
        migrations.AlterField(
            model_name='country',
            name='production_country',
            field=models.CharField(max_length=100, verbose_name='olke adi'),
        ),
    ]
