# Generated by Django 3.1.5 on 2021-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210329_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derinlik',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='genislik',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='yukseklik',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
